AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - script/**/*
    - vendor/**/*
    - bin/**/*
  TargetRubyVersion: 2.2

Rails:
  Enabled: true

Documentation:
  Enabled: false

MethodLength:
  Severity: warning
  Max: 15

Style/AndOr:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 9

GuardClause:
  MinBodyLength: 3

Style/Lambda:
  Exclude:
      - config/**/*
