inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**/*
    - script/**/*
    - vendor/**/*
    - bin/**/*
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Documentation:
  Enabled: false

MethodLength:
  Severity: warning
  Max: 15

Style/AndOr:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/ClassLength:
  Max: 150

GuardClause:
  MinBodyLength: 3

Style/Lambda:
  Exclude:
    - config/**/*

Style/AsciiComments:
  Enabled: false
