sudo: false
cache: bundler
language: ruby
rvm:
  - 2.3.8
services:
- redis-server
before_install:
  - echo ${SIDEKIQ_CREDS}
- bundle config gems.contribsys.com ${SIDEKIQ_CREDS}
before_script:
- bundle exec rake db:create db:migrate RAILS_ENV=test
script:
- bundle exec rubocop -R
- bundle exec rspec spec
