sudo: false
cache: bundler
language: ruby
rvm:
  - 2.2.3
services:
- redis-server
before_script:
- bundle exec rake db:create db:migrate RAILS_ENV=test
script:
- bundle exec rubocop -R
- bundle exec rspec spec
