dist: xenial
cache: bundler
language: ruby
addons:
- postgresql: "10"
services:
- redis-server
before_install:
- bundle config gems.contribsys.com ${SIDEKIQ_CREDS}
before_script:
- bundle exec rake db:create db:migrate RAILS_ENV=test
script:
- bundle exec rubocop -R
- bundle exec rspec spec
