dist: focal
cache: bundler
language: ruby
addons:
  postgresql: 13
  apt:
    packages:
      - graphviz
services:
  - redis-server
  - postgresql
env:
  global:
    # These variables are intentionally blank in order establish the connection to the Postgresql 11 server:
    - DB_ENV_POSTGRESQL_USER_TEST=
    - DB_ENV_POSTGRESQL_USER=
    - DB_ENV_POSTGRESQL_PASS_TEST=
    - DB_ENV_POSTGRESQL_PASS=
    - DB_PORT_5432_TCP_ADDR_TEST=
    - DB_PORT_5432_TCP_ADDR=
    - DB_PORT_5432_TCP_PORT_TEST=5433
branches:
  only:
    - master
    - staging
before_install:
  - gem install bundler -v 2.2.28
  - bundle config gems.contribsys.com ${SIDEKIQ_CREDS}
before_script:
  - bundle exec rails db:setup RAILS_ENV=test
script:
  - bundle exec standardrb
  - bundle exec rspec spec
  - bundle exec bundle audit check --update
  - bundle exec brakeman -A -q --no-pager --ensure-latest
after_success:
  - bin/deploy/build_and_upload_erd.sh
