name: Ruby Cache

on:
  push:
    branches: [master]

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        env:
          BUNDLE_GEMS__CONTRIBSYS__COM: ${{ secrets.BUNDLE_GEMS__CONTRIBSYS__COM }}
